Repository FourLeaves4/Client, pull requests merged in 2024-12, with the labels that each got.

#13 Feature plan screen
  assets/Mascot.png
  assets/MessageBox.png
  package-lock.json
  package.json
  src/components/DataDisplay.jsx
  src/components/LabeledDivider.jsx
  src/components/MascotWithMessage/Mascot.jsx
  src/components/MascotWithMessage/MascotWithMessage.jsx
  src/components/MascotWithMessage/MessageBox.jsx
  src/components/TimeDisplay.jsx
  src/components/WeeklyProgressChart.jsx
  src/pages/PlanScreen.jsx
Labels: 🔥 Feat

#17 [Feat] Feature/grass
  src/components/GrassBoard.jsx
  src/pages/MyScreen.jsx
Labels: 🔥 Feat

#18 [Feat]Feature/weekly progress chart
  App.js
  assets/AndroidCharacter.png
  assets/AndroidCharacterSelected.png
  assets/BackEndCharacter.png
  assets/BackEndCharacterSelected.png
  assets/FrontEndCharacter.png
  assets/FrontEndCharacterSelected.png
  assets/HomeAndroidCharacter.png
  assets/HomeBackEndCharacter.png
  assets/HomeFrontEndCharacter.png
  assets/HomeIOSCharacter.png
  assets/HomeNovaCharacter.png
  assets/IOSCharacter.png
  assets/IOSCharacterSelected.png
  assets/NovaCharacter.png
  assets/NovaCharacterSelected.png
  assets/circle-arrow-left.png
  assets/circle-arrow-right.png
  assets/logo.png
  src/components/Character/CharacterButton.jsx
  src/components/Character/CharacterDisplay.jsx
  src/components/Character/Header.jsx
  src/components/Character/PaginationDots.jsx
  src/components/GrassBoard.jsx
  src/components/ProfileCard.jsx
  src/components/WeeklyProgressChart.jsx
  src/pages/HomeScreen.jsx
  src/pages/MyScreen.jsx
  src/pages/character.jsx
  src/pages/question.jsx
  src/pages/start.jsx
Labels: 🔥 Feat

#21 wip: 백엔드에서 레벨 데이터를 가져오는 설정 추가
  src/components/LevelLabel.jsx
Labels: wip

#22 [Wip] Feature log out
  assets/Out.png
  src/components/LogOut.jsx
Labels: wip

#23 [Feat] Feature my screen
  assets/adaptive-icon.png
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  src/pages/MyScreen.jsx
Labels: 🔥 Feat

#25 chore: 백엔드 연동을 위한 기본 토대 구축 (MascotWithMessage에 avg 적용 준비)
  src/pages/PlanScreen.jsx
Labels: enhancement

#26 Chore: 백엔드에서 미션 데이터를 가져오는 기능의 기본 토대 설정
  src/components/LevelBarSection.jsx
Labels: enhancement

#28 Feat: 개발자 단계 화면에 레벨 시스템 및 남은 단계 정보 추가
  src/pages/DeveloperStageScreen.jsx
Labels: 🔥 Feat

#29 Feat: 프로필 카드 클릭 시 'MyScreen'으로 네비게이션 추가
  src/components/ProfileCard.jsx
Labels: 🔥 Feat

#31 Refactor: 정적인 데이터에서 동적 API 호출로 변경 및 스타일 개선
  src/components/GrassBoard.jsx
Labels: 🔥 Feat

#32 Feature character
  assets/1st.png
  assets/2nd.png
  assets/3rd.png
  assets/Ad.png
  assets/Ai.png
  assets/AndroidCharacter.png
  assets/AndroidCharacterSelected.png
  assets/BackEndCharacter.png
  assets/BackEndCharacterSelected.png
  assets/Be.png
  assets/ExamplePhoto_01.png
  assets/ExamplePhoto_02.png
  assets/ExamplePhoto_03.png
  assets/Fe.png
  assets/FrontEndCharacter.png
  assets/FrontEndCharacterSelected.png
  assets/HomeAndroidCharacter.png
  assets/HomeBackEndCharacter.png
  assets/HomeFrontEndCharacter.png
  assets/HomeIOSCharacter.png
  assets/HomeNovaCharacter.png
  assets/IOSCharacter.png
  assets/IOSCharacterSelected.png
  assets/Mascot.png
  assets/Mascot1.png
  assets/NovaCharacter.png
  assets/NovaCharacterSelected.png
  assets/Nv.png
  assets/aiProfile.png
  assets/io.png
  assets/고화질.be.png
  assets/고화질ad.png
  assets/고화질fe.png
  assets/고화질ios2.png
  assets/고화질nv.png
  assets/고화질선택.nv.png
  assets/고화질선택ad.png
  assets/고화질선택ad2.png
  assets/고화질선택be.png
  assets/고화질선택fe.png
  assets/고화질선택ios.png
  assets/고화질선택ios2.png
  assets/살려줘.png
  src/components/AIProfile.jsx
  src/components/Character/CharacterButton.jsx
  src/pages/PlanScreen.jsx
  src/pages/character.jsx
  src/pages/start.jsx
Labels: 🔥 Style

#33 ✨ feat: 레벨별 뱃지 추가 및 ImageComponent 리팩토링
  assets/badge1.png
  assets/badge2.png
  assets/badge3.png
  assets/badge4.png
  assets/badge5.png
  src/components/ImageComponent.jsx
  src/pages/DeveloperStageScreen.jsx
Labels: 🔥 Feat

#37 ✨ 리팩토링: 백엔드 API 호출 제거 및 동적 데이터 처리를 위한 Props로 대체 🔧
  src/components/CompletionLabel.jsx
  src/components/DevelopStep.jsx
  src/components/DeveloperStageButton.jsx
  src/components/GrassBoard.jsx
  src/components/LevelBarSection.jsx
  src/components/LevelLabel.jsx
  src/components/profileSection.jsx
  src/pages/MyScreen.jsx
Labels: enhancement, 🔥 Feat

#38 ✨ feat: 백엔드에서 사용자 프로필 데이터 가져오기 및 미션 진행 상황 업데이트
  src/pages/DeveloperStageScreen.jsx
Labels: 🔥 Feat

#40 Feature plan screen
  src/pages/PlanScreen.jsx
Labels: 🔥 Feat
